services:
  airflow:
    image: apache/airflow:2.8.1-python3.11
    command: standalone
    ports:
      - "8085:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey123
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin123
      APP_DATABASE_URL: mysql+pymysql://jobuser:jobpassword123@host.docker.internal:3306/job_recommendation
      GROQ_API_KEY: gsk_your_key_here
      MILVUS_HOST: host.docker.internal
      MINIO_ENDPOINT: host.docker.internal:9000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow_data:/opt/airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  airflow_data:
